#!/usr/bin/env python3
"""
Merge StepKV component-ablation summaries from two models into one LaTeX/Markdown table.

Usage:
    python merge_stepkv_ablation_two_models.py \
        --model_a results/stepkv_ablation_qwen25/summary.json --label_a "Qwen2.5-7B" \
        --model_b results/stepkv_ablation_llama31/summary.json --label_b "Llama-3.1-8B" \
        --output_dir results/stepkv_component_ablation_merged

Each input is a summary.json produced by run_stepkv_component_ablation.py.
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Any, Dict, List, Tuple

DATASET_ORDER = ("hotpotqa", "2wiki", "musique")

ABLATION_LABELS = {
    "full": "Full StepKV",
    "no_repeat": "w/o repeat",
    "no_novelty": "w/o novelty",
    "no_success": "w/o success",
    "no_cite": "w/o cite",
    "no_token": "w/o token score",
    "no_step": "w/o step score",
}


def _load_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict) or "datasets" not in data:
        raise ValueError(f"Invalid summary json: {path}")
    return data


def _dataset_display_name(ds: str) -> str:
    return {
        "hotpotqa": "HotpotQA",
        "2wiki": "2WikiMultihopQA",
        "musique": "MuSiQue",
    }.get(ds, ds)


def _latex_escape(text: str) -> str:
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
    )


def _ordered_datasets(summary: Dict[str, Any]) -> List[str]:
    present = list(summary.get("datasets", {}).keys())
    ordered = [ds for ds in DATASET_ORDER if ds in present]
    ordered.extend(ds for ds in present if ds not in ordered)
    return ordered


def _ordered_ablations(summary: Dict[str, Any]) -> List[str]:
    if summary.get("ablation_order"):
        return list(summary["ablation_order"])
    first_ds = next(iter(summary["datasets"].values()))
    return list(first_ds.get("ablations", {}).keys())


def _get_cell(summary: Dict[str, Any], ds: str, ablation: str) -> Tuple[float, float, float, float]:
    row = summary["datasets"][ds]["ablations"][ablation]
    full = summary["datasets"][ds]["ablations"]["full"]
    em = float(row["em"])
    f1 = float(row["f1"])
    delta_em = em - float(full["em"])
    delta_f1 = f1 - float(full["f1"])
    return em, f1, delta_em, delta_f1


def _write_markdown(
    summaries: List[Tuple[str, Dict[str, Any]]],
    datasets: List[str],
    ablations: List[str],
    output_md: str,
) -> None:
    lines = [
        "# StepKV component ablation (two models)",
        "",
        "| Model | Dataset | Ablation | EM | F1 | ΔEM | ΔF1 |",
        "|---|---|---|---:|---:|---:|---:|",
    ]
    for model_label, summary in summaries:
        for ds in datasets:
            ds_name = _dataset_display_name(ds)
            for ab in ablations:
                em, f1, dem, df1 = _get_cell(summary, ds, ab)
                label = ABLATION_LABELS.get(ab, ab)
                if ab == "full":
                    dem_s = "--"
                    df1_s = "--"
                else:
                    dem_s = f"{dem:+.2f}"
                    df1_s = f"{df1:+.2f}"
                lines.append(
                    f"| {model_label} | {ds_name} | {label} | {em:.2f} | {f1:.2f} | {dem_s} | {df1_s} |"
                )
    os.makedirs(os.path.dirname(output_md) or ".", exist_ok=True)
    with open(output_md, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _write_tex_two_models(
    summaries: List[Tuple[str, Dict[str, Any]]],
    datasets: List[str],
    ablations: List[str],
    output_tex: str,
    meta: Dict[str, Any],
) -> None:
    n_models = len(summaries)
    n_ds = len(datasets)
    cols_per_model = 2 * n_ds
    col_spec = "l" + ("cc" * n_ds) * n_models

    n = meta.get("num_samples", "--")
    rho = meta.get("cache_ratio", "--")
    rho_str = f"{rho:.2f}" if isinstance(rho, float) else str(rho)

    lines = [
        r"% Auto-generated by merge_stepkv_ablation_two_models.py",
        r"\begin{table*}[t]",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        rf"\caption{{Component ablation of StepKV on three benchmarks ($N={n}$, $\rho={rho_str}$). "
        rf"Results for {n_models} models; each dataset reports EM / F1 (\%). "
        r"$\Delta$EM in the footnote is relative to \textit{Full StepKV} on the same model and dataset.}}",
        r"\label{tab:stepkv-ablation-two-models}",
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
    ]

    model_header = ["Variant"]
    cmid_model = []
    col_idx = 2
    for model_label, _ in summaries:
        model_header.append(rf"\multicolumn{{{cols_per_model}}}{{c}}{{{_latex_escape(model_label)}}}")
        cmid_model.append(rf"\cmidrule(lr){{{col_idx}-{col_idx + cols_per_model - 1}}}")
        col_idx += cols_per_model
    lines.append(" & ".join(model_header) + r" \\")
    lines.extend(cmid_model)

    ds_header = [" "]
    cmid_ds = []
    col_idx = 2
    for _ in summaries:
        for ds in datasets:
            ds_header.append(rf"\multicolumn{{2}}{{c}}{{{_dataset_display_name(ds)}}}")
            cmid_ds.append(rf"\cmidrule(lr){{{col_idx}-{col_idx + 1}}}")
            col_idx += 2
    lines.append(" & ".join(ds_header) + r" \\")
    lines.extend(cmid_ds)

    metric_header = [" "]
    for _ in summaries:
        for _ds in datasets:
            metric_header.extend(["EM", "F1"])
    lines.append(" & ".join(metric_header) + r" \\")
    lines.append(r"\midrule")

    for ab in ablations:
        label = ABLATION_LABELS.get(ab, ab)
        row_label = r"\textbf{Full StepKV}" if ab == "full" else _latex_escape(label)
        cells = [row_label]
        for _model_label, summary in summaries:
            for ds in datasets:
                em, f1, _, _ = _get_cell(summary, ds, ab)
                cells.append(f"{em:.2f}")
                cells.append(f"{f1:.2f}")
        lines.append(" & ".join(cells) + r" \\")

    lines.append(r"\bottomrule")
    lines.extend([r"\end{tabular}", ""])

    for model_label, summary in summaries:
        lines.append(r"\vspace{0.35em}")
        lines.append(r"{\footnotesize")
        lines.append(rf"\textbf{{{_latex_escape(model_label)} $\Delta$EM:}} ")
        delta_chunks = []
        for ab in ablations:
            if ab == "full":
                continue
            label = ABLATION_LABELS.get(ab, ab)
            ds_deltas = []
            for ds in datasets:
                _, _, dem, _ = _get_cell(summary, ds, ab)
                ds_deltas.append(f"{_dataset_display_name(ds)} {dem:+.2f}")
            delta_chunks.append(f"{label} ({', '.join(ds_deltas)})")
        lines.append("; ".join(delta_chunks) + ".")
        lines.append(r"}")

    lines.append(r"\end{table*}")
    os.makedirs(os.path.dirname(output_tex) or ".", exist_ok=True)
    with open(output_tex, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Merge two StepKV ablation summaries into one LaTeX table.")
    parser.add_argument("--model_a", required=True, help="Path to summary.json for model A.")
    parser.add_argument("--label_a", default="Model A", help="Display name for model A.")
    parser.add_argument("--model_b", required=True, help="Path to summary.json for model B.")
    parser.add_argument("--label_b", default="Model B", help="Display name for model B.")
    parser.add_argument(
        "--output_dir",
        default="results/stepkv_component_ablation_merged",
        help="Directory for merged md/tex/json outputs.",
    )
    args = parser.parse_args()

    summary_a = _load_json(args.model_a)
    summary_b = _load_json(args.model_b)
    summaries = [(args.label_a, summary_a), (args.label_b, summary_b)]

    datasets_a = _ordered_datasets(summary_a)
    datasets_b = _ordered_datasets(summary_b)
    if datasets_a != datasets_b:
        raise ValueError(f"Dataset mismatch: {datasets_a} vs {datasets_b}")
    datasets = datasets_a

    ablations_a = _ordered_ablations(summary_a)
    ablations_b = _ordered_ablations(summary_b)
    if ablations_a != ablations_b:
        raise ValueError(f"Ablation mismatch: {ablations_a} vs {ablations_b}")
    ablations = ablations_a

    meta = {
        "num_samples": summary_a.get("num_samples", summary_b.get("num_samples")),
        "cache_ratio": summary_a.get("cache_ratio", summary_b.get("cache_ratio")),
        "seed": summary_a.get("seed", summary_b.get("seed")),
        "models": [
            {"label": args.label_a, "summary_path": os.path.abspath(args.model_a)},
            {"label": args.label_b, "summary_path": os.path.abspath(args.model_b)},
        ],
    }

    merged = {
        "meta": meta,
        "datasets": datasets,
        "ablation_order": ablations,
        "models": {args.label_a: summary_a, args.label_b: summary_b},
    }

    os.makedirs(args.output_dir, exist_ok=True)
    out_json = os.path.join(args.output_dir, "summary_merged.json")
    out_md = os.path.join(args.output_dir, "ablation_table_two_models.md")
    out_tex = os.path.join(args.output_dir, "ablation_table_two_models.tex")

    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    _write_markdown(summaries, datasets, ablations, out_md)
    _write_tex_two_models(summaries, datasets, ablations, out_tex, meta)

    print(f"[INFO] Saved merged json: {out_json}")
    print(f"[INFO] Saved merged md:   {out_md}")
    print(f"[INFO] Saved merged tex:  {out_tex}")


if __name__ == "__main__":
    main()
